// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA_jsk6-6pUnAlEeRov_2Z8H2X4cvJZCc',
    appId: '1:985770518005:android:ed0f7842d5c932053cecbc',
    messagingSenderId: '985770518005',
    projectId: 'weatherforecast-362c9',
    databaseURL: 'https://weatherforecast-362c9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'weatherforecast-362c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1gSLur12fymSdPgdFeWLCljj5PJycZ8A',
    appId: '1:985770518005:ios:c59220017be05cdd3cecbc',
    messagingSenderId: '985770518005',
    projectId: 'weatherforecast-362c9',
    databaseURL: 'https://weatherforecast-362c9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'weatherforecast-362c9.appspot.com',
    iosClientId: '985770518005-f6tek34qpbn61p07hhfjn2j23ho469i4.apps.googleusercontent.com',
    iosBundleId: 'com.bsuir.weather',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyC_0gLN2HZrJVEcU2YcmtxN9k0n807bsnE",
      authDomain: "weatherforecast-362c9.firebaseapp.com",
      databaseURL: "https://weatherforecast-362c9-default-rtdb.europe-west1.firebasedatabase.app",
      projectId: "weatherforecast-362c9",
      storageBucket: "weatherforecast-362c9.appspot.com",
      messagingSenderId: "985770518005",
      appId: "1:985770518005:web:6dc8c5554dbd4bdb3cecbc",
      measurementId: "G-DWKJ9L2CJT"
  );
}
